---

- name: 'Test status de master y nodos'
  hosts: master
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: 'Test 1'
      include_role:
        name: test-nodes

    - name: 'Test 2'
      include_role:
        name: test-pods

    - name: 'Test 3'
      include_role:
        name: test-services
    
    - name: 'Test 4'
      include_role:
        name: test-pv-pvc
